type: hugo
name: adsense-home
title: "Search123"
description: "Practical guides to search smarter, work faster, and stay safe online"
source: template
language: en
created: 2026-02-19
root_domain: true
