type: static
name: word-counter
title: "Word Counter"
description: "Count words, characters, sentences and paragraphs instantly"
source: https://github.com/letchagan/Simple-Word-counter
license: MIT
language: en
created: 2026-02-25
