type: static
name: json-linter
title: "JSON Formatter & Validator"
description: "Format, validate, minify and lint JSON data online"
source: https://github.com/njoylab/json-linter-tool
license: MIT
language: en
created: 2026-02-25
