#!/usr/bin/env bash
# generate-content-plan.sh - Generate a content plan for a Hugo site using AI.
# Reads site metadata from site.yaml, calls AI to produce article topics,
# and saves them to content-plans/{site-name}.yaml (outside sites/).
#
# Usage: ./scripts/generate-content-plan.sh <site-name> [topic_count] [schedule]
#
# Defaults come from config.yaml (content.default_schedule, content.default_topic_count)
# and can be overridden via arguments or SF_CONTENT_SCHEDULE env var.

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$REPO_ROOT/scripts/lib/config.sh"
source "$REPO_ROOT/scripts/lib/logging.sh"
source "$REPO_ROOT/scripts/lib/llm.sh"

SITE_NAME="${1:?Usage: generate-content-plan.sh <site-name> [topic_count] [schedule]}"
TOPIC_COUNT="${2:-${SF_CONTENT_TOPIC_COUNT:-25}}"
SCHEDULE="${3:-${SF_CONTENT_SCHEDULE:-weekly}}"

SITE_DIR="$REPO_ROOT/sites/$SITE_NAME"
SITE_YAML="$SITE_DIR/site.yaml"
PLAN_DIR="$REPO_ROOT/content-plans"
PLAN_FILE="$PLAN_DIR/$SITE_NAME.yaml"

if [[ ! -f "$SITE_YAML" ]]; then
  log_error "site.yaml not found: $SITE_YAML"
  exit 1
fi

mkdir -p "$PLAN_DIR"

# Read site metadata
SITE_TITLE=$(yq '.title // ""' "$SITE_YAML")
SITE_DESC=$(yq '.description // ""' "$SITE_YAML")
SITE_LANG=$(yq '.language // "en"' "$SITE_YAML")

if [[ -z "$SITE_TITLE" || "$SITE_TITLE" == "null" ]]; then
  log_error "site.yaml missing title field"
  exit 1
fi

log_info "Generating content plan for '$SITE_NAME' ($TOPIC_COUNT topics)"
log_info "Provider: $SF_AI_PROVIDER ($SF_AI_MODEL)"

# Determine content language for the prompt
LANG_INSTRUCTION=""
if [[ "$SITE_LANG" == "zh" || "$SITE_LANG" == "zh-"* ]]; then
  LANG_INSTRUCTION="Write all titles and keywords in Chinese (简体中文)."
elif [[ "$SITE_LANG" == "ja" ]]; then
  LANG_INSTRUCTION="Write all titles and keywords in Japanese (日本語)."
else
  LANG_INSTRUCTION="Write all titles and keywords in English."
fi

# Build AI prompts
SYSTEM_PROMPT="You are an SEO content strategist. Given a website's niche, title, and description, generate a content plan of article topics. Each topic must:
- Target a specific long-tail keyword phrase
- Be answerable in 800-1500 words
- Have clear search intent (informational, how-to, comparison, or list)
- Not overlap significantly with other topics in the list
- Be practical and useful for the target audience

Output ONLY a valid YAML array. No markdown code fences. No explanations.
Each item must have exactly three fields: title (string), keywords (comma-separated string), and slug (URL-friendly English slug, lowercase letters/numbers/hyphens only, max 60 chars).
The slug must ALWAYS be in English regardless of the title language — it should be a concise English translation or summary of the title.

Example output format:
- title: \"Best Pour-Over Technique for Beginners\"
  keywords: \"pour over coffee, pour over technique, beginner pour over\"
  slug: \"best-pour-over-technique-beginners\"
- title: \"French Press vs AeroPress: Complete Comparison\"
  keywords: \"french press vs aeropress, coffee press comparison\"
  slug: \"french-press-vs-aeropress-comparison\""

USER_PROMPT="Website title: ${SITE_TITLE}
Description: ${SITE_DESC}
Language: ${SITE_LANG}
Number of topics: ${TOPIC_COUNT}
${LANG_INSTRUCTION}

Generate ${TOPIC_COUNT} SEO-optimized article topics for this website."

# Call AI
log_step "Calling ${SF_AI_PROVIDER} API..."
PLAN_YAML=$(llm_generate "$SYSTEM_PROMPT" "$USER_PROMPT")

if [[ -z "$PLAN_YAML" ]]; then
  log_error "AI returned empty content"
  exit 1
fi

# Clean response: strip markdown code fences if present
PLAN_YAML=$(echo "$PLAN_YAML" | sed '/^```.*$/d')

# Trim leading/trailing whitespace
PLAN_YAML=$(echo "$PLAN_YAML" | sed '/^$/d' | sed '1s/^[[:space:]]*//')

# Validate it's parseable YAML
if ! echo "$PLAN_YAML" | yq '.' > /dev/null 2>&1; then
  log_error "AI returned invalid YAML for content plan"
  log_info "Raw output (first 500 chars):"
  echo "$PLAN_YAML" | head -c 500
  exit 1
fi

# Validate it's an array
ITEM_COUNT=$(echo "$PLAN_YAML" | yq 'length')
if [[ "$ITEM_COUNT" -lt 1 ]]; then
  log_error "AI returned empty content plan"
  exit 1
fi

# Add status: pending to each item
TOPICS_YAML=$(echo "$PLAN_YAML" | yq '.[].status = "pending"')

# Derive niche from title
NICHE=$(echo "$SITE_TITLE" | tr '[:upper:]' '[:lower:]')

# Extract target keywords (top 10 unique keywords from all topics)
TARGET_KEYWORDS=$(echo "$PLAN_YAML" | yq '.[].keywords' | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sort -u | head -10)
TK_YAML="[]"
while IFS= read -r kw; do
  [[ -z "$kw" ]] && continue
  TK_YAML=$(echo "$TK_YAML" | yq ". + [\"$kw\"]")
done <<< "$TARGET_KEYWORDS"

# Write content plan file
cat > "$PLAN_FILE" << EOF
# Content plan for ${SITE_NAME}
# Auto-generated by generate-content-plan.sh
# Managed separately from sites/ — see docs/automated-content.md
site: ${SITE_NAME}
niche: "${NICHE}"
publishing_schedule: "${SCHEDULE}"
last_generated: ""
EOF

# Append target_keywords and topics via yq (use temp files for reliable loading)
TK_TMPFILE=$(mktemp)
TOPICS_TMPFILE=$(mktemp)
echo "$TK_YAML" > "$TK_TMPFILE"
echo "$TOPICS_YAML" > "$TOPICS_TMPFILE"
yq -i ".target_keywords = load(\"$TK_TMPFILE\")" "$PLAN_FILE"
yq -i ".topics = load(\"$TOPICS_TMPFILE\")" "$PLAN_FILE"
rm -f "$TK_TMPFILE" "$TOPICS_TMPFILE"

log_ok "Content plan generated: $ITEM_COUNT topics for '$SITE_NAME'"
log_info "Schedule: $SCHEDULE"
log_info "Plan file: content-plans/$SITE_NAME.yaml"
log_info "View plan: yq '.topics' content-plans/$SITE_NAME.yaml"
